services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=[your username]
      - SPRING_DATASOURCE_PASSWORD=[your password]
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=[username]
      - POSTGRES_PASSWORD=[your password]
